name: CI via Bun

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2.1.2

      - name: Checkout 
        uses: actions/checkout@v6.0.2

      - name: Install dependencies
        run: bun ci

      - name: Build
        run: bun run build 

      - name: Test (via Bun)
        run: bun test

      - name: Test (via Jest)
        run: bun run test

      - name: Lint
        run: bun lint || exit 0
